# Generated by Django 5.1.4 on 2024-12-16 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='major_id',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='schedule',
            name='major',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.major'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.subject'),
        ),
    ]
