# Generated by Django 5.1.4 on 2024-12-16 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_schedule_major_id_remove_schedule_subject_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='room',
            field=models.CharField(choices=[('G01', 'G01'), ('G02', 'G02'), ('G03', 'G03'), ('G04', 'G04'), ('G05', 'G05'), ('G06', 'G06'), ('G07', 'G07'), ('G08', 'G08'), ('G09', 'G09'), ('G10', 'G10'), ('101', '101'), ('102', '102'), ('103', '103'), ('104', '104'), ('105', '105'), ('106', '106'), ('107', '107'), ('108', '108'), ('109', '109'), ('110', '110'), ('201', '201'), ('202', '202'), ('203', '203'), ('204', '204'), ('205', '205'), ('206', '206'), ('207', '207'), ('208', '208'), ('209', '209'), ('210', '210'), ('301', '301'), ('302', '302'), ('303', '303'), ('304', '304'), ('305', '305'), ('306', '306'), ('307', '307'), ('308', '308'), ('309', '309'), ('310', '310')], max_length=10),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('major', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.major')),
            ],
        ),
    ]
