# Generated by Django 5.1.4 on 2024-12-16 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_schedule_day_alter_schedule_room_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='teacher_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.teacher'),
        ),
    ]
