# Generated by Django 5.1.4 on 2024-12-16 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_schedule_teacher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='teacher_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.teacher'),
        ),
    ]
