# Generated by Django 5.1.4 on 2024-12-16 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_schedule_teacher_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='teacher_name',
        ),
        migrations.AddField(
            model_name='subject',
            name='major',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.major'),
        ),
    ]
