# Generated by Django 5.1.4 on 2024-12-16 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_remove_schedule_teacher_name_subject_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.teacher'),
        ),
    ]
